//AUTH CONSTANTS
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const DELETE_SUCCESS = 'DELETE_SUCCESS';

export const DELETE_ERROR = 'DELETE_ERROR';

//BUCKETLIST CONSTANTS
//export const ITEM_DELETED = 'ITEM_DELETED';

//export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';

export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';

export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const DISPLAY_ITEMS = 'DISPLAY_ITEMS';

export const DELETE_ITEM = 'DELETE_ITEM';

export const UPDATE_ITEM = 'UPDATE_ITEM';

//LOCATION CONSTANTS
export const GET_USER_LOCATION = 'GET_USER_LOCATION';

export const GET_CUSTOM_LOCATION = 'GET_CUSTOM_LOCATION';

export const GET_CUSTOM_LOCATION_ERROR = 'GET_CUSTOM_LOCATION_ERROR';

//RECOMMENDATION CONSTANTS
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS';

export const RECOMMENDATIONS_TO_LIST = 'RECOMMENDATIONS_TO_LIST';

export const RECOMMENDATIONS_ERROR = 'RECOMMENDATIONS_ERROR';

//Wishlist constants
export const GET_WISHLIST = 'GET_WISHLIST';

export const WISHLIST_TO_LIST = "WISHLIST_TO_LIST";

export const WISHLIST_ERROR = 'WISHLIST_ERROR';

export const WISHLIST_DELETE_SUCCESS = 'WISHLIST_DELETE_SUCCESS';

export const WISHLIST_DELETE_ERROR = 'WISHLIST_DELETE_ERROR';

//My Memories constants
export const GET_MEMORIES = 'GET_MEMORIES';

export const MEMORIES_TO_LIST = "MEMORIES_TO_LIST";

export const MEMORIES_ERROR = 'MEMORIES_ERROR';

export const MEMORIES_DELETE_SUCCESS = 'MEMORIES_DELETE_SUCCESS';

export const MEMORIES_DELETE_ERROR = 'MEMORIES_DELETE_ERROR';
//PROFILE CONSTANTS
export const GET_USER_INFORMATION_SUCCESS = 'GET_USER_INFORMATION_SUCCESS';

export const GET_USER_INFORMATION_ERROR = 'GET_USER_INFORMATION_ERROR';

//SEARCH CONSTANTS
export const GET_SEARCH_LIST = 'GET_SEARCH_LIST';
export const GET_SEARCH_BUCKET_LIST = 'GET_SEARCH_BUCKET_LIST';

//CALENDAR CONSTANTS
export const GET_CALENDAR_ON_SUCCESS = 'GET_CALENDAR_ON_SUCCESS';
export const GET_CALENDAR_ERROR = 'GET_CALENDAR_ERROR';
//export const GET_USER_AVAILABILITY = 'GET_USER_AVAILABILITY';

